engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
- server/spec/*
exclude_paths:
- "templates/"
- node_modules/**/*




